# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42698caa3674786e04275d4d079f63060894ccbd2202f9366137f9b3d107d956b9d1b313a879490aa20e7e9499adfdf62a668d32541ef4c6e19f5e7012a8bd9a

test:
  secret_key_base: 04bd1213b5a042c0eb87f01da03db4e935da8ae2e03d481a1aadce4b1418803f85d9551f2ff0cb71f328cee4e58e41799ee3d4da0f721b0e002750153381a1d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
